schema_version = "1.0.0"

id = "InstanceToCSV"
version = "1.0.0"
name = "Instance Info to CSV"
tagline = "Export Linked Instance Data"
maintainer = "WSSStone"
type = "add-on"

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64"]